#26 Documento de elicitação de personas
Requisitos-de-Software/2021.1-Ingresso.com pull request #34
Opened 2021-08-09 12:31 UTC by Joao-Moura

## Descrição 

- Foi criado o documento contendo as personas pensadas para o projeto. No total foram pensadas 6 personas, sendo 4 personas primárias, 1 persona secundária e uma antipersona

## Resolve (Issues)
- #26 

## Tarefas gerais realizadas
* Adição do documento de personas
* Adição de fotos
* Modificação do mkdocs

2021-08-09 18:18 UTC, VitorLamego requested changes
Parabéns pelo trabalho João !! Está muito bom como um todo e parabéns pela criatividade na hora de criar as personas. 

Uma mudança que eu gostaria de solicitar seria na diminuição das fotos das personas, acredito que acabou ficando muito grande, o que ocasionou um certo incômodo na estética da página.

2021-08-09 18:18 UTC, VitorLamego commented on docs/elicitacao/personas.md
> +<p style="text-align: justify; text-indent: 20px">Para a criação de um produto de qualidade, é importante compreender quem são os usuários, quais são seus ojetivos e suas necessidades. De forma a fac
A utilização do 'então' no final da frase ficou deslocada. Na frase: "De forma a facilitar esse entendimento então". Acredito que sem ficaria melhor.

2021-08-09 18:18 UTC, VitorLamego commented on docs/elicitacao/personas.md
> +<p style="text-align: justify; text-indent: 20px"><b>Personas</b> conforme descrito por Cooper <i>et al.</i> (2007), Pruitt e Adlin (2006) e Cooper (1999), são personagens fictícios de um grupo de us
Faltou a acentuação no 'mantem'

2021-08-09 18:18 UTC, VitorLamego commented on docs/elicitacao/personas.md
> +|<b>Expectativas:</b>|Por seu desejo de viajar para os diversos estados Brasileiros e por gostar bastante da simplicidade, espera que um aplicativo de cinemas seja capaz de prover meios simples para
Corrigir a palavra 'Brasileiros' para 'brasileiros'.

2021-08-09 18:18 UTC, VitorLamego commented on docs/elicitacao/personas.md
> +|<b>Expectativas:</b>|Apesar de ser criança, aoenas espera que o aplicativo ajude sua mãe na compra de ingressos para sessões de cinemas que gosta de ir com seus amigos.|
Erro na palavra 'aoenas'.

2021-08-09 20:16 UTC, Joao-Moura commented
Tamanho das fotos alteradas e correções gramaticais feitas.

2021-08-09 21:51 UTC, VitorLamego approved these changes
Ótimo trabalho !

2021-08-10 01:43 UTC, CarlosFiuza requested changes
Ótimo trabalho João, personas muito bem detalhadas e com certeza ajudarão na elicitação de requisitos!
Deixei apenas dois comentários na revisão para correção de alguns erros na redação.

2021-08-10 01:43 UTC, CarlosFiuza commented on docs/elicitacao/personas.md
> +<p style="text-align: justify; text-indent: 20px">Para a criação de um produto de qualidade, é importante compreender quem são os usuários, quais são seus ojetivos e suas necessidades. De forma a fac
"objetivos" ta escrito incorretamente

2021-08-10 01:43 UTC, CarlosFiuza commented on docs/elicitacao/personas.md
> +|<b>Tarefas:</b>|Por todo o período da manhã e da tarde ensinsa literatura em uma escola de ensino fundamental onde trabalha. Pela noite, prepara suas aulas do dia seguinte e aproveita suas últimas h
"ensina" está escrito incorretamente

2021-08-10 11:48 UTC, Joao-Moura commented
Corrigido chefe

2021-08-10 13:36 UTC, CarlosFiuza approved these changes
Show de bola!

2021-08-10 13:37 UTC, merged