#24 Justificativa de Escolha do App
Requisitos-de-Software/2021.1-Ingresso.com pull request #36
Opened 2021-08-09 17:57 UTC by VitorLamego

## Descrição 

- Foi adicionado ao arquivo principal do mkdocs a justificativa de escolha do aplicativo Ingresso.com pelo grupo.
## Resolve (Issues)
-  #24 

## Tarefas gerais realizadas
* Edição do documento index

2021-08-09 19:34 UTC, Joao-Moura requested changes
Muito bom os novos parágrafos. Só deixei algumas correções que acho que deixarão melhor o texto. Parabéns.

2021-08-09 19:34 UTC, Joao-Moura commented on docs/index.md
> +    Após algumas conversas e votações, o grupo optou por escolher o aplicativo Ingresso.com após analisar que o trabalho voltado para a área de requisitos seria muito benéfico para todos, uma vez que
- Acredito ficaria bom a utilização da palavra "bastante" na frase: "[...], é um aplicativo com _bastante_ espaço para [...]".
- E retirar a palavra "também" da frase: "[...] adicionar novas funcionalidades também.".

2021-08-09 19:34 UTC, Joao-Moura commented on docs/index.md
> +    Além disso, sabemos que devido à pandemia os evento e alguns estabelecimentos tiveram que fechar suas portas por conta de um bem maior, o que impactou diretamente o aplicativo em questão. Portant
- Em vez da palavra "[...] o momento _parece_ proício [...]" seria melhor usar o verbo "é".

2021-08-09 23:07 UTC, Joao-Moura approved these changes
Perfeito, parabéns.

2021-08-10 13:29 UTC, thiagohdaqw approved these changes
Bom trabalho

2021-08-10 13:29 UTC, merged