#21 Documento de elicitação observação participativa
Requisitos-de-Software/2021.1-Ingresso.com pull request #37
Opened 2021-08-10 02:32 UTC by CarlosFiuza

## Descrição 
- Foi criado o documento de observação participativa com os requisitos elicitados durante a observação, ao total de 57 requisitos.

## Resolve (Issues)
- #21 

## Tarefas gerais realizadas
* Criação do documento
* Preenchimento do documento
* Adição do documento no mkdocs

2021-08-10 13:43 UTC, Joao-Moura requested changes
Show de mais mano, parabéns. Deixei algumas mudanças de padronização e outras sobre os requisitos. De resto é isso.

2021-08-10 13:43 UTC, Joao-Moura commented on docs/elicitacao/observacao_participativa.md
> +|OP26|O sistema deve reproduzir trailer do filme com vídeo do YouTube|<p style="text-align: center">RF</p>|
Achei meio confunso ter a OP25 e OP26, acredito que só 1 é suficiente

2021-08-10 13:43 UTC, Joao-Moura commented on docs/elicitacao/observacao_participativa.md
> +|OP34|O usuário deve poder filtrar sessões do cinema por Tipo de Exibição|<p style="text-align: center">RF</p>|
Só para confirmar, esse requisito (OP34) é diferetente da OP23 ?

2021-08-10 13:43 UTC, Joao-Moura commented on docs/elicitacao/observacao_participativa.md
> +|OP52|O usuário deve poder pesquisar cinemas por iniciativas de prevenção|<p style="text-align: center">RF</p>|
Não acho que seja necessário esse requisito (OP52), até porque é algo temporário.

2021-08-10 13:53 UTC, CarlosFiuza commented on docs/elicitacao/observacao_participativa.md
> +## 3. Resultado
mas o padrão não é resultado?

2021-08-10 13:57 UTC, CarlosFiuza commented on docs/elicitacao/observacao_participativa.md
> +|OP34|O usuário deve poder filtrar sessões do cinema por Tipo de Exibição|<p style="text-align: center">RF</p>|
Sim

2021-08-10 13:58 UTC, CarlosFiuza commented on docs/elicitacao/observacao_participativa.md
> +|OP52|O usuário deve poder pesquisar cinemas por iniciativas de prevenção|<p style="text-align: center">RF</p>|
mas e se a pandemia não acabar nunca? kkk
Já que foi explicíta a versão do app acho que é necessário ter todos os requisitos daquela versão.

2021-08-10 14:06 UTC, Joao-Moura commented on docs/elicitacao/observacao_participativa.md
> +## 3. Resultado
Só se vc tiver feito algum passo extra, tipo: storyboard, persona, como o brainstorm foi feito. No caso da observação vc só olha e ja tem os requisitos.

2021-08-10 14:07 UTC, Joao-Moura commented on docs/elicitacao/observacao_participativa.md
> +|OP52|O usuário deve poder pesquisar cinemas por iniciativas de prevenção|<p style="text-align: center">RF</p>|
Pode crer kkkkkkk. Então acho que não tem problema não

2021-08-10 20:10 UTC, CarlosFiuza commented on docs/elicitacao/observacao_participativa.md
> +## 3. Resultado
Mas a observação exige um método, que é se passar pelo usuário, logo gera resultados.

2021-08-10 22:11 UTC, Joao-Moura commented on docs/elicitacao/observacao_participativa.md
> +## 3. Resultado
Uhm, faz sentido. Entrão coloca:

## 3. Resultado
## 4. Requisitos
## 5. Referências

2021-08-11 02:12 UTC, Joao-Moura approved these changes
O cara se recusa a botar o tópico requisitos com 4 kkkkkkkk. Mais é isso, perfeito. Parabéns.

2021-08-16 00:21 UTC, vital14 approved these changes
Ao meu ver, tudo ok, bom trabalho

2021-08-17 01:33 UTC, merged