#18 5W2H
Requisitos-de-Software/2021.1-Ingresso.com pull request #39
Opened 2021-08-10 19:02 UTC by VitorLamego

## Descrição 

- Foi adicionado o documento do 5W2H relacionado ao projeto em questão.
## Resolve (Issues)
- #18 

## Tarefas gerais realizadas
* Criação do documento
* Adição do 5W2H

2021-08-10 19:15 UTC, vital14 commented on docs/elicitacao/5w2h.md
> +<p style="text-align: justify; text-indent: 20px">Dentro da Engenharia de Software, é uma metodologia muito utilizada nas etapas de requisitos, uma vez que traz mais clareza e profundidade para os st
acredito que o correto aqui seria user story

2021-08-10 19:15 UTC, vital14 commented on docs/elicitacao/5w2h.md
> +<p style="text-align: justify; text-indent: 20px">Aplicativo Mobile para a compra online de ingressos de cinemas e eventos espalhados pelas cidades do Brasil. Além disso o aplicativo permite que apsi
aqui está escrito apsixonados, corrigir para apaixonados

2021-08-11 00:31 UTC, RcleydsonR requested changes
Curti bastante o documento, está muito bem padronizado e de fácil entendimento, encontrei alguns erros gramaticais, mas consertando isso é aprovação certeira !

2021-08-11 00:31 UTC, RcleydsonR commented on docs/elicitacao/5w2h.md
> +<p style="text-align: justify; text-indent: 20px">Quando o aplicativo da Ingresso.com foi lançado a emprese pertencia ao grupo B2W - Companhia Global de Varejo. A partir de 2015, passou a fazer parte
a empresa* ao invés de a emprese

2021-08-11 00:31 UTC, RcleydsonR commented on docs/elicitacao/5w2h.md
> +<p style="text-align: justify; text-indent: 20px">Segundo José Roberto, diretor de TI da empresa em 2018, a Ingresso.com possui uma equipe específica para desenvolvimento mobile, unindo grandes desen
trabalharam ao invés de trabalaram.

2021-08-16 00:15 UTC, vital14 approved these changes
Não encontrei mais problemas além dos já corrigidos

2021-08-16 02:54 UTC, RcleydsonR approved these changes
Agora sim, ficou muito bom! Parabéns !

2021-08-16 02:54 UTC, merged