[WIP] #25 Elicitação - Introspecção
Requisitos-de-Software/2021.1-Ingresso.com pull request #40
Opened 2021-08-14 02:40 UTC by thiagohdaqw

## Descrição 

Trabalhando nas introspecções.

- Adição da introdução
- Adição das introspecções
- Adição das referencias

## Resolve (Issues)
- #25

## Tarefas gerais realizadas
* Adição do documento de introspeção

2021-08-16 15:14 UTC, VitorLamego requested changes
Trabalho muito bem feito, deixei algumas sugestões de mudanças. Mas fora isso parabéns pelo trabalho !!

2021-08-16 15:14 UTC, VitorLamego commented on docs/elicitacao/introspeccao.md
> +A introspecção consiste no ato de tentar entender as propriedades que um sistema deve ter para que seja bem sucedido. Baseia-se em imaginar o que você gostaria que o sistema tivesse para realizar uma
Eu trocaria a utilização desse "dada tarefa" por "determinada tarefa"

2021-08-16 15:14 UTC, VitorLamego commented on docs/elicitacao/introspeccao.md
> +### Ao acessar o aplicativo
Acho plausível adicionar: "Deve mostrar os cinemas abertos próximos ao usuário", "Deve ter uma área informando as medidas de prevenção durante a pandemia", "Deve ter uma área para selecionar a cidade que deseja"

2021-08-16 15:14 UTC, VitorLamego commented on docs/elicitacao/introspeccao.md
> +- Os cinemas devem apresentar os horários das sessões do filme.
Eu completaria esse tópico com: "Os cinemas devem apresentar os horários das sessões do filme nos próximos dois dias"

2021-08-16 16:15 UTC, thiagohdaqw commented
> Trabalho muito bem feito, deixei algumas sugestões de mudanças. Mas fora isso parabéns pelo trabalho !!

feito, meu patrao

2021-08-16 17:59 UTC, Joao-Moura requested changes
Muito bem feito o documento, só uma coisa que eu acho que valha a pena modificar para deixar em padrão com os outros documentos (além de facilitar pra gente identificar na priorização qual é o requisito) seria utilizar a tabela ID, Descrição, TIpo de Requisitos.
Ex:
## 2. Introspecções [...]
### Ao acessar [...]
|ID|Descrição|TIpo de Requisitos|
|--|--|--|
|I01|Deve apresentar os filmes mais [...]|Requisito Funcional
|I02|Não há necessidade de autenticação [...]|Requisito Não Funcional
|...|...|...|

### Ao escolher [...]
|ID|Descrição|TIpo de Requisitos|
|--|--|--|
|I14|Deve apresentar informações  [...]|Requisito Funcional
|...|...|...|

Ps.: Se for fazer essa tabela não esqueça as legendas

No mais é isso, só deixei mais duas correções que ficariam melhor. Parabéns.

2021-08-16 17:59 UTC, Joao-Moura commented on docs/elicitacao/introspeccao.md
> +- Pode compartilhar o filme.
Aqui acho que em vez de "Pode [...]" ficaria melhor "Poder [...]"

2021-08-16 17:59 UTC, Joao-Moura commented on docs/elicitacao/introspeccao.md
> +- Pode comprar com uma conta criada.
Acredito que ficaria melhor sendo: "Pode comprar com um conta criada no domínio", ou algo do tipo

2021-08-17 02:20 UTC, thiagohdaqw commented
Ótima sugestão, joão. Eu optei por criar uma seção separada porque, com a tabela misturada com os títulos, a legibilidade e o entendimento do fluxo de pensamento seriam prejudicados.

2021-08-17 11:20 UTC, Joao-Moura requested changes
Perfeito, agora sim ficou bem nice. Só uma coisinha de número que eu notei kkkkkk.

2021-08-17 11:20 UTC, Joao-Moura commented on docs/elicitacao/introspeccao.md
> +## 3. Referências
Mudar pra 4, porque o 3 são os requisitos.

2021-08-17 20:38 UTC, Joao-Moura approved these changes
Show, não achei mais nenhum erro. Parabéns.

2021-08-17 20:40 UTC, VitorLamego approved these changes
Parabéns Thiago !! Ótimo trabalho.

2021-08-17 20:47 UTC, merged