#22 Documento de elicitação de entrevistas
Requisitos-de-Software/2021.1-Ingresso.com pull request #41
Opened 2021-08-17 11:40 UTC by Joao-Moura

## Descrição 

- Adição do documento contendo entrevistas, bem como os requisitos elicicitados.

## Resolve (Issues)
- #22

## Tarefas gerais realizadas
* Adição das entrevistas
* Adição da tabela de requisitos
* Modificação do mkdocs

2021-08-17 23:19 UTC, CarlosFiuza requested changes
Muito bom trabalho!
Deixei apenas algumas sugestões de correções.

2021-08-17 23:19 UTC, CarlosFiuza commented on mkdocs.yml
> +    - Entrevistas: "elicitacao/entrevistas.md""
tem aspas a mais nessa linha, ta quebrando o documento bonitão

2021-08-17 23:19 UTC, CarlosFiuza commented on mkdocs.yml
> +    - Entrevistas: "elicitacao/entrevistas.md""
a lista de documentos deve estar ordenada em ordem alfabética

2021-08-17 23:53 UTC, Joao-Moura commented on mkdocs.yml
> +    - Entrevistas: "elicitacao/entrevistas.md""
Pegadinha isso daqui em

2021-08-19 02:28 UTC, RcleydsonR approved these changes
Sou companheiro e vou aprovar o PR, kkkkkk brincs, curti bastante o documento, principalmente os requisitos não funcionais elicitados, o único problema que vi ortográfico foi no uso do por que na 5º pergunta do questionário, como ele é usado ao final da frase com o sentido de perguntar qual razão ou o motivo, o uso correto seria o "por quê" separado e acentuado, mas de resto meus parabéns !

2021-08-19 02:29 UTC, CarlosFiuza approved these changes

2021-08-19 12:07 UTC, merged