#20 Documento de brainstorming
Requisitos-de-Software/2021.1-Ingresso.com pull request #42
Opened 2021-08-17 20:49 UTC by RcleydsonR

## Descrição 

Foi elaborado o documento de brainstorming através de uma reunião via discord com os integrantes: Rafael, Vitor Lamego e Thiago. Foram abordadas algumas perguntas para promover uma dinâmica bacana na elicitação e após essas perguntas foram elicitados os requisitos em conjunto pela equipe.

## Resolve (Issues)
- #20 

## Tarefas gerais realizadas
* Feito um brainstorming através de perguntas chaves.
* Elicitado os requisitos baseados em algumas respostas e discussões da equipe

2021-08-17 22:43 UTC, Joao-Moura requested changes
Muito massa o brainstorm de vocês. A única coisa que eu gostaria de apontar é que algumas novas funcionalidades foram citadas no brainstorm (como a dos eventos próximos) e não foram citadas na tabela de requisitos. Acho que a tabela ficaria ainda melhor se fossem adicionados esses novos requisitos pensados. No mais é isso ficou show, parabéns.

2021-08-19 02:45 UTC, RcleydsonR commented
Bacana @Joao-Moura, agradeço o feedback, mesmo sendo uma possível funcionalidade vou agregá-la  a tabela.

2021-08-19 12:01 UTC, Joao-Moura approved these changes
Perfeito, parabéns a todos

2021-08-20 14:41 UTC, vital14 approved these changes
Ótimo trabalho, parabéns

2021-08-20 14:42 UTC, merged