#31 adicionando documento relacionado ao questionario
Requisitos-de-Software/2021.1-Ingresso.com pull request #43
Opened 2021-08-18 21:50 UTC by vital14

Adição dos dados elicitados por meio do questionário
## Descrição 
Criação do questionário e adição dos dados obtidos nas respostas ao documento a ser inserido relacionado ao questionário
## Resolve (Issues)
- #31
## Tarefas gerais realizadas
*  Criação do questionário
* Escrita dos dados

2021-08-19 00:02 UTC, Joao-Moura requested changes
Muito bom o documento como um todo, estou deixando algumas mudanças e já vou citar uma que é geral do arquivo
- A figura só tem a legenda, faltou a fonte (ex.: Fonte: Autor)

No mais é isso, valeu pelo PR

2021-08-19 00:02 UTC, Joao-Moura commented on docs/elicitacao/questionario.md
> +| 6 | Deixar claro nas lojas para que o aplicativo serve para que mais pessoas conheçam | Não funcional|
Mesma coisa, não é um requisito

2021-08-19 00:02 UTC, Joao-Moura commented on docs/elicitacao/questionario.md
> +>WIEGERS, Karl; BEATTY, Joy. "Software Requirements". Microsoft Press, 2013.
Seguir o padrão de referências dos outros documentos do repositório

2021-08-19 00:02 UTC, Joao-Moura commented on docs/elicitacao/questionario.md
> +|Número | Requisito | Tipo |
Seguir o padrão da tabela de requisitos dos outros documentos

2021-08-19 12:51 UTC, CarlosFiuza requested changes
Bom trabalho!
Documento muito bem construído e vital para nosso projeto, parabéns!
Deixei apenas algumas sugestões de mudanças.

2021-08-19 12:51 UTC, CarlosFiuza commented on docs/elicitacao/questionario.md
> +As respostas listadas no nosso questionário nos ajudaram a enchergar qual o público que mais utiliza o aplicativo, quais são as motivações para a utilização do aplicativo entre outras coisas apenas c
Aqui enxergar está escrito errado.

2021-08-19 12:51 UTC, CarlosFiuza commented on docs/elicitacao/questionario.md
> +<figcaption> Figura 7: Questão para saber se o usuário sabe que existem outras funcionaliades no aplicativo</figcaption>
Aqui funcionalidades está escrito errado

2021-08-19 12:51 UTC, CarlosFiuza commented on docs/elicitacao/questionario.md
> +
Só faltou a fonte da tabela, nesse caso: "Fonte: Autor"

2021-08-19 16:35 UTC, Joao-Moura approved these changes
Perfeito da minha parte. Parabéns.

2021-08-20 14:51 UTC, CarlosFiuza approved these changes

2021-08-20 15:22 UTC, merged