#28 Priorização First Things First
Requisitos-de-Software/2021.1-Ingresso.com pull request #44
Opened 2021-08-20 00:23 UTC by thiagohdaqw

## Descrição 

- A priorização dos requisitos elicitados foi feita com a tecnica First Things First
## Resolve (Issues)
- #28

## Tarefas gerais realizadas
* Priorização First Things First documentada

2021-08-20 20:07 UTC, Joao-Moura requested changes
Muito bem feita essa técnica de priorização. Só deixando algumas alterações, mais de resto é isso. Parabéns

2021-08-20 20:07 UTC, Joao-Moura commented on docs/priorizacao/first_things_first.md
> +<p style="text-align: justify; text-indent: 20px">Há uma necessidade para uma priorização de requisitos mais rigorosa e analítica [1]. A First Things First é uma técnica que ajuda a relacionar as fun
- Não entendi a primeira frase, achei ela desconexa do restante do parágrafo. Seria algo melhor do tipo: "Ao se produzir um software, sempre há uma necessidade [...]"
- Na segunda frase da pra começar com: "A <b>First Things First</b> (aqui usar o bold do html mesmo) é uma dessas técnicas de priorização, que [...]" e no final da mesma frase: "[...] entrega par elas", não entendi esse elas
- E por fim, quando vcs usam o [1] quebra totalmente o texto, adicionar pelo menos quem escreveu (ex.: "Assim, segundo tal tal tal [...]") ou de que livro/artigo foi retirado.

2021-08-20 20:07 UTC, Joao-Moura commented on docs/priorizacao/first_things_first.md
> +    <img src="../../assets/priorizacao/formula_prioridade.png" width="300px"/>
Aqui, por ser uma foto (ou até mesmo fórmulas) precisa de uma legenda e fonte

2021-08-20 20:07 UTC, Joao-Moura commented on docs/priorizacao/first_things_first.md
> +<p style="text-align: justify; text-indent: 20px">Além dos passos apresentados, levamos em consideração alguns pontos apresentados por [1] para estimarmos a priorização, sendo eles: </p>
Novamente a review do [1] citada anteriormente

2021-08-20 20:07 UTC, Joao-Moura commented on docs/priorizacao/first_things_first.md
> +### 2.1 Requisitos de Referência
Tópico 2.1 seguido do 3. Corrigir para 3.1

2021-08-20 20:07 UTC, Joao-Moura commented on docs/priorizacao/first_things_first.md
> +## 3. Referências
Tópico 3 sendo que o último foi 3.1. Mudar para 4

2021-08-20 20:07 UTC, Joao-Moura commented on docs/priorizacao/first_things_first.md
> +<p style="text-align: justify; text-indent: 20px">[[1] Wiegers, K.; Beatty, J. Software Requirements. <b>Microsoft Press</b>. ed. 3, 2013.</p>
"[[1] Wiegers [...]", tem dois "["

2021-08-21 16:20 UTC, Joao-Moura approved these changes
Perfeito, parabéns.

2021-08-23 12:02 UTC, RcleydsonR approved these changes
O documento está muito bem elaborado, parabéns pelo esforço galera, agora é só corrigir o pequeno conflito de branch para dar o merge !

2021-08-23 12:10 UTC, merged