#63 Modelagem ágil iStar
Requisitos-de-Software/2021.1-Ingresso.com pull request #68
Opened 2021-09-06 16:57 UTC by Joao-Moura

## Descrição 

- Adição do documento e da diagramação referente a técnica iStar
## Resolve (Issues)
- #63 

## Tarefas gerais realizadas
* Criação do documento
* Adição dos diagramas

2021-09-08 12:07 UTC, RcleydsonR requested changes
Achei excelente o documento rapaziada, estão de parabéns !
Só deixei alguns comentários de pequenas correções e um pra dar uma melhor explicação do por que de não ter utilizado tal abordagem.

2021-09-08 12:07 UTC, RcleydsonR commented on docs/modelagem/istar.md
> +
Não entendi o motivo de não possuir um modelo rationale para Notícia e acabei sentindo falta, se puderem explicar eu ficaria grato !

2021-09-08 12:07 UTC, RcleydsonR commented on docs/modelagem/istar.md
> +<p style="text-align: justify; text-indent: 20px"> Para o projeto em questão, foram desenvolvidos quatro diferentes diagramas, no software piStar tool [3] que detalham e analisam diferentes contextos
Creio que não tem vírgula depois de diagramas na segunda linha.

2021-09-08 14:12 UTC, Joao-Moura commented on docs/modelagem/istar.md
> +
Existir existe, porém quando eu e o Lamego estavamos produzindo esses diagramas não encontramos a necessidade, nem conseguimos pensar em um modelo rationale para a notícia que valesse a pena ser adicionado ao documento.

2021-09-09 02:30 UTC, RcleydsonR commented on docs/modelagem/istar.md
> +
Perfeito então João, agradeço o esclarecimento !

2021-09-09 02:31 UTC, RcleydsonR approved these changes
Trabalho excepcional galera ! Parabéns.

2021-09-09 14:20 UTC, thiagohdaqw approved these changes
Trabalho muito bem feito, parabéns a todos! So deixo alguns comentários opcionais:
- Acho que numerar a secção do iStar ficaria mais agradável, por exemplo: 3.1 Cinema; 3.2 Notícia; etc.
- As imagens com mais informações poderiam ser mostradas com o zoom padrão habilitado, como acontece no diagrama de caso de uso. `<img class="zoom" src="....">`
- Acho que em "Acessar ingresso possuídos" deveria ser "Acessar ingresso**s** possuídos".
![image](https://user-images.githubusercontent.com/54081877/132702926-e5b97266-06b3-495f-b5f0-4d8e319fdbdf.png)

2021-09-09 14:26 UTC, thiagohdaqw requested changes

2021-09-09 14:26 UTC, thiagohdaqw commented on docs/modelagem/istar.md
> +<h6 align = "center">Fonte: Autores, pela ferramenta iStar tool [3].</h6>
O nome da ferramenta é piStar tool

2021-09-09 14:28 UTC, thiagohdaqw commented on docs/modelagem/istar.md
> +<h6 align = "center">Fonte: Autores, pela ferramenta iStar tool [3].</h6>
nas referencias tbm 

![image](https://user-images.githubusercontent.com/54081877/132704701-761e9be6-6ff4-4e94-b926-99824a4a5bb4.png)

2021-09-09 15:17 UTC, thiagohdaqw approved these changes
Bom trabalho time

2021-09-09 15:31 UTC, merged