Modelagem Product Backlog
Requisitos-de-Software/2021.1-Ingresso.com pull request #70
Opened 2021-09-08 23:07 UTC by CarlosFiuza

## Descrição 

- Criação do documento de histórias de usuário e adição dos resultados.
- Criação do documento de product backlog e adição dos resultados.
## Resolve (Issues)
- #69 

## Tarefas gerais realizadas
* Criação do documento de Histórias de Usuário
* Adição dos Épicos, features e histórias de usuário
* Criação documento Product Backlog
* Adição da tabela de backlog

2021-09-09 01:20 UTC, Joao-Moura requested changes
Muito massa a organização dos documentos. Encontrei uns errinhos e deixei umas sugestões de melhoria, mas no mais é isso. Parabéns.

2021-09-09 01:20 UTC, Joao-Moura commented on docs/modelagem/historias_usuario.md
> +## 5. Referência
Mudar para tópico 6

2021-09-09 01:20 UTC, Joao-Moura commented on docs/modelagem/historias_usuario.md
> +#### Legenda:
Aqui acho melhor trocar o #### por `<b>Legenda:</b>`

ps.: Se fizer isso mesmo, bota um espaço entre legenda e épico porque se não quebra o layout da página

2021-09-09 01:20 UTC, Joao-Moura commented on docs/modelagem/product_backlog.md
> +<table>
Aqui na tabela em vez de priorizar por alta, média ou baixa, usa o MoSCoW

2021-09-09 15:32 UTC, Joao-Moura commented on docs/modelagem/product_backlog.md
> +<table>
Tinha esquecidod e comentar também, adiciona a rastreabilidade de qual dos requisitos é que vem

2021-09-09 22:59 UTC, VitorLamego requested changes
Pessoal, bom trabalho na realização do Product Backlog e das Histórias de Usuário.

Deixei comentários referentes a alguns erros gramaticais e alguma mudanças dentro do documento de acordo com o meu ponto de vista.

2021-09-09 22:59 UTC, VitorLamego commented on mkdocs.yml
> +    - Histórias de Usuário: "modelagem/historias_usuario.md"
Respeitar a ordenação alfabética das páginas.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/product_backlog.md
> +| 1.1    | 08/09 | Adição das prioridades de cada item no backlog | Victor Lima |
Versão repetida.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/product_backlog.md
> +            <td id="celula">Eu, como usuário, desejo criar uma conta para eu ter acesso as funcionalidades completas do aplicativo.</td>
faltou a crase em: "acesso às funcionalidades..."

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/product_backlog.md
> +            <td id="celula">Eu, como desenvolvedor, desejo realizar a validadação dos dados preenchidos no formulário de cadastramento para garantir que são reais.</td>
No meu ponto de vista, colocar "Eu, como desenvolvedor" gerou certa dúvida. Acredito que essas histórias de usuário que vocês colocaram para os desenvolvedores se encaixe mais em "Eu, como sistema". São atividaddes desempenhadas pelo sistema, acho que não faz tanto sentido inserir o desenvolvedor nesse cenário de história de usuário.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/product_backlog.md
> +            <td id="celula">Eu, como usuário, desejo fazer login para entrar na minha conta e aproveitar das funcionalidades do ingresso.com</td>
Mudar "ingresso.com" para "Ingresso.com" por ser o nome de uma empresa.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/product_backlog.md
> +            <td id="celula">Eu, como usuário, desejo esclarecer dúvidas e/ou enviar solicitações de atendimento para o ingresso.com para compreender melhor o aplicativo.</td>
Mudar "ingresso.com" para "Ingresso.com" por ser o nome de uma empresa.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/product_backlog.md
> +            <td id="celula">Média</td>
Avaliar se essa US realmente tem prioridade Média. Sem a opção de escolha do cinema não tem como o usuário comprar ingresso. Na US abaixo de pesquisa a prioridade está como alta, mas acredito que a visualização seja mais importante do que a própria pesquisa.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/product_backlog.md
> +            <td id="celula">Eu, como usuário, desejo visualizar as informações sobre o filme para decidir se quero assistí-lo ou não.</td>
O verbo "assistir" no sentido de ver não admite esse pronome. O correto seria assistir a ele. Da forma como está o verbo tem sentido de "ajudar".

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/product_backlog.md
> +            <td id="celula">Eu, como desenvolvedor, desejo disponibilizar trailer do filme do youtube para o aplicativo para que o usuário consiga assistí-lo.</td>
O verbo "assistir" no sentido de ver não admite esse pronome. O correto seria assistir a ele. Da forma como está o verbo tem sentido de "ajudar".

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/product_backlog.md
> +            <td id="celula" rowspan="3"><a href="../historias_usuario/#feature-15-noticia"> F15 </a><br>Noticia</td>
Faltou o acento em "Notícia".

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/product_backlog.md
> +    </thead>
Centralizar o cabeçalho da tabela. Não está alinhado com o conteúdo.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| E06 - Engajamento | Engloba toda a parte de manter o usuário engajado.  | -> Noticia <br/> -> Destaques <br/> |
"Noticia" sem acento.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Descrição | Eu, como usuário, desejo criar uma conta para eu ter acesso as funcionalidades completas do aplicativo. |
Retirar o segundo "eu"da frase e acrescentar a crase: "para ter acesso às funcionalidades...".

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Descrição | Eu, como desenvolvedor, desejo realizar a validadação dos dados preenchidos no formulário de cadastramento para garantir que são reais. |
A mesma ideia do outro documento no que se relaciona à utilização de "Eu, como desenvolvedor", parece que é função da pessoa que programou o aplicativo e não do sistema.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Critérios de Aceitação | Deve conter as seguintes opções: <br/> <b> Nome </b> <br/> -> Apenas caracteres do alfabeto.<br/> <b> E-mail </b> <br/>-> Ser email válido. <br/> <b> Senha </b> <br/>-> Pos
Acredito que acrescentando uma linha em branco após cada opção e sua restrição vai melhorar a visualização dessa tabela. Ficou um pouco poluída a leitura.

E "digitos" faltou o acento.

E "telefone"iniciando a frase está com letra inicial minúscula.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Descrição | Eu, como usuário, desejo fazer login para entrar na minha conta e aproveitar das funcionalidades do ingresso.com |
"aproveitar as funcionalidades" e colocar "Ingresso.com" com letra inicial em maiúsculo por ser o nome de uma empresa.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Critérios de Aceitação | Deve conter as seguintes opções: <br/> <b> E-mail </b> <br/>-> Ser email válido. <br/> <b> Senha </b> <br/>-> Possuir ao menos 8 digitos. <br/> |
Mesma questão do espaçamento anteriormente citado e a acentuação em "digitos".

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Nome | Vizualizar cartões salvos. |
Corrigir para "Visualizar".

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Descrição | Eu, como usuário, desejo esclarecer dúvidas e/ou enviar solicitações de atendimento para o ingresso.com para compreender melhor o aplicativo. |
"Ingresso.com".

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Critérios de Aceitação | -> Opção para ordenar por nome. <br/> -> Opção para ordenar por proximidade. <br/> -> Opção para visualizar cinemas fechados. <br/> Opção para visualizar cinemas abertos. <
Faltou a "-> " em "Opção para visualizar cinemas abertos."

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Descrição | Eu, como usuário, desejo visualizar filmes que em breve estarão nos cinemas para que eu possa me programar para assistir o filme. |
Remover "o filme" do final da frase para evitar repetição.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Descrição | Eu, como usuário, desejo visualizar as informações sobre o filme para decidir se quero assistí-lo ou não. |
Mesma correção do verbo "assistir" do documento anterior.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Descrição | Eu, como usuário, desejo visualizar o trailer do filme para descobrir do que se trata o filme. |
Remover "o filme" do final da frase para evitar repetição.

2021-09-09 22:59 UTC, VitorLamego commented on docs/modelagem/historias_usuario.md
> +| Descrição | Eu, como desenvolvedor, desejo disponibilizar trailer do filme do youtube para o aplicativo para que o usuário consiga assistí-lo. |
Mesma correção do verbo "assistir" do documento anterior.

2021-09-10 03:10 UTC, CarlosFiuza commented on docs/modelagem/historias_usuario.md
> +#### Legenda:
Ficou exatamente a mesma coisa kkk

2021-09-10 14:06 UTC, Joao-Moura commented on docs/modelagem/historias_usuario.md
> +#### Legenda:
Fica não, lá no lado do mkdocs o tópico se estiver como bold some e fica mais organizado

2021-09-10 17:39 UTC, Joao-Moura approved these changes
Perfeito, da minha parte não encontrei mais nada de errado. Parabéns.

2021-09-12 23:49 UTC, CarlosFiuza commented on docs/modelagem/historias_usuario.md
> +| Critérios de Aceitação | Deve conter as seguintes opções: <br/> <b> Nome </b> <br/> -> Apenas caracteres do alfabeto.<br/> <b> E-mail </b> <br/>-> Ser email válido. <br/> <b> Senha </b> <br/>-> Pos
adicionar linha em branco acaba quebrando a tabela

2021-09-13 13:37 UTC, VitorLamego approved these changes
Parabéns pelo trabalho !!

2021-09-13 14:07 UTC, merged