Validacao protótipo
Requisitos-de-Software/2021.1-Ingresso.com pull request #93
Opened 2021-09-20 03:17 UTC by RcleydsonR

## Descrição 

- Nesse documento se encontra a validação dos requisitos levantados a partir da prototipação, mais informações vide wiki.
## Resolve (Issues)
- #91 

## Tarefas gerais realizadas
* Realizado o protótipo de baixa/média fidelidade
* Documentado na wiki todo o processo

2021-09-20 11:37 UTC, Joao-Moura requested changes
Show, muito bom o documento, deixei duas correções. No mais é isso, parabéns.

2021-09-20 11:37 UTC, Joao-Moura commented on docs/validacao/prototipo.md
> +<p style="text-align: justify; text-indent: 20px">Como o escopo do aplicativo é muito grande e não havia possibilidade de fazer um protótipo tão grande em tão pouco tempo, deicidimos selecionar algum
Corrigir a palavra "deicidimos"

2021-09-20 11:37 UTC, Joao-Moura commented on docs/validacao/prototipo.md
> +<p style="text-align: justify; text-indent: 20px">Consideramos o app do Ingresso.com em produção na play store [2] como nosso stakeholder, ou seja, a validação será baseada no que temos implementado
Esse parágrafo achei meio desnecessário, porque ele já foi citado anteriormente. Refazer ele ou apagar.

2021-09-20 14:55 UTC, VitorLamego approved these changes
O que eu tinha para comentar o João já deixou para vocês !! Sendo assim, parabéns pelo trabalho de Validação. Corrigindo o que foi citado pelo João, por mim pareceu tudo certo.

2021-09-21 00:25 UTC, RcleydsonR commented on docs/validacao/prototipo.md
> +<p style="text-align: justify; text-indent: 20px">Consideramos o app do Ingresso.com em produção na play store [2] como nosso stakeholder, ou seja, a validação será baseada no que temos implementado
Decidi por apagá-lo, fez mais sentido ! Obg

2021-09-21 00:25 UTC, RcleydsonR commented
Pronto galera, muito obrigado pelo feedback !

2021-09-21 01:02 UTC, Joao-Moura approved these changes
Perfeito, parabéns.

2021-09-21 01:03 UTC, merged